channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - aiohttp
  - argon2-cffi
  - async-timeout
  - async_generator
  - attrs
  - blas
  - bleach
  - blinker
  - bokeh
  - bottleneck
  - brotlipy
  - c-ares
  - ca-certificates
  - catalogue
  - catboost
  - certifi
  - cffi
  - cftime
  - chardet
  - cloudpickle
  - confuse
  - cryptography
  - cudatoolkit=9.2  # Retain specific version if needed
  - curl
  - cycler
  - cymem
  - cython-blis
  - cytoolz
  - dask
  - dask-core
  - dataclasses
  - decorator
  - defusedxml
  - dill
  - distributed
  - entrypoints
  - freetype
  - fsspec
  - future
  - hdf4
  - hdf5
  - heapdict
  - htmlmin
  - idna
  - imagehash
  - imbalanced-learn
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libllvm10
  - libnetcdf
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libxgboost
  - lightgbm
  - llvmlite
  - locket
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - missingno
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msgpack-numpy
  - msgpack-python
  - multidict
  - murmurhash
  - nb_conda
  - nb_conda_kernels
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - netcdf4
  - networkx
  - ninja
  - notebook
  - numba
  - numpy
  - numpy-base
  - olefile
  - openssl
  - packaging
  - pandas
  - pandas-profiling
  - pandoc
  - pandocfilters
  - partd
  - pexpect
  - phik
  - pickleshare
  - pillow
  - pip
  - plac
  - preshed
  - proj
  - prometheus_client
  - prompt_toolkit
  - psutil
  - ptyprocess
  - py-xgboost
  - pyasn1
  - pycparser
  - pydeprecate
  - pydot
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pyproj
  - pyqt
  - pyreadstat
  - pyrsistent
  - pysocks
  - python=3.7.9
  - python-dateutil
  - python-libarchive-c
  - pytorch
  - pytorch-lightning
  - pywavelets
  - pywin32
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - regex
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - six
  - smart_open
  - sniffio
  - snowballstemmer
  - sortedcontainers
  - soupsieve
  - spacy
  - sqlite
  - srsly
  - terminado
  - testpath
  - thinc
  - threadpoolctl
  - tk
  - tokenizers
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - tzlocal
  - ujson
  - urllib3
  - vc
  - vs2015_runtime
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - wincertstore
  - wrapt
  - xarray
  - xgboost
  - xlrd
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
  - torchvision